// <auto-generated />
namespace CBA.CBAMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class watever : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(watever));
        
        string IMigrationMetadata.Id
        {
            get { return "201507202045507_watever"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
